# Generated by Django 4.2 on 2023-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                (
                    "course_number",
                    models.IntegerField(
                        help_text="Course Number represents the Course ID"
                    ),
                ),
            ],
        ),
    ]
