# Generated by Django 4.2 on 2023-05-14 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="contributor's first name", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="contributor's last name", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="contributor's email", max_length=254),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of movie", max_length=100)),
                ("date", models.DateField(verbose_name="Movie released date")),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="name of publisher", max_length=50),
                ),
                ("website", models.URLField(help_text="publisher's website")),
                (
                    "email",
                    models.EmailField(help_text="publisher's email", max_length=254),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="review text")),
                (
                    "rating",
                    models.IntegerField(help_text="rating that given by reviewer"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="date and time of the review"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="the movie that this review is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MoviesListApp.movie_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ACTOR", "Actor"), ("DIRECTOR", "Director")],
                        max_length=20,
                        verbose_name="contributor's role in the movie",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MoviesListApp.contributor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MoviesListApp.movie_info",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie_info",
            name="contributor",
            field=models.ManyToManyField(
                through="MoviesListApp.MovieContributor", to="MoviesListApp.contributor"
            ),
        ),
        migrations.AddField(
            model_name="movie_info",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MoviesListApp.publisher",
            ),
        ),
    ]
